### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by KhoraLee** [KhoraLee/Lenovo-Ideapad-Slim3-14iil05-Hackintosh#2]
### **Related to Software**
- [x] ~Upgrade OC (0.5.9 -> 0.6.0) ~
- [x] ~Update Kexts (Lilu, AppleAlc, WEG, etc...)~
- [ ] Refactor SSDT to work only on Hackintosh

### **Related to Hardware**
- [x] ~Fix Audio~ (Temporarily fix using FakePCIID)
- [x] ~Fix I2C TrackPad~ [VoodooI2C Patch](https://github.com/KhoraLee/VoodooI2C/commit/cafd08abe5a392f15d58d657e2a06f546338bf4e) This will be official after new version of VoodooI2C is released (Dev build will be used in EFI)
- [ ] Fix Power Management 
- [ ] USB 15 port Limit Patch
